config/routes.rb
Rails.application.routes.draw do
  resources :currencies
  resources :categories
  resources :type_changes
  resources :changes
  resources :exchange_parities

  root 'currencies#index'

end

app/models/change.rb
class Change < ActiveRecord::Base
  belongs_to        :type_change

  before_create     :set_start
  after_create      :close_before_change 
  
  validates :type_change_id, :amount, presence: true

  def set_start
    self.start_dt=Time.now
  end

  def close_before_change
    if self.type_change.all_changes.size > 1
      changeHistory=self.type_change.all_changes.last(2).first 
      changeHistory.end_dt=self.start_dt
      changeHistory.save
    end 
  end

end

app/controllers/changes_controller.rb
class ChangesController < ApplicationController
  before_action :set_change, only: [:show , :edit]
  
  def index
    @changes=Change.all.order(:type_change_id, :id)
  end

  
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_change
      @change = Change.find(params[:id])
    end

    def change_params
      params.require(:change).permit(:type_change_id ,:amount )
    end

end

app/helpers/changes_helper.rb
module ChangesHelper
end

app/views/changes/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <%= simple_form_for(@change) do |f| %>
    <% if @change.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@change.errors.count, "error") %> prohibited this type change from being saved:</h2>
      <ul>
        <% @change.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="field">
      <label>Moneda desde:</label>
      <%= select_tag( :currency_from_id, options_for_select(@currencies.map { |c| [c.name, c.id]  } ) ,:id => 'change_currency_from', :name => "change[currency_from_id]" , :class => "select2" ) %>
    </div>

    <div class="field">
     <label>Moneda hasta:</label>
     <%= select_tag( :currency_to_id, options_for_select(@currencies.map { |c| [c.name, c.id]  } ) , :id => 'change_currency_to', :name => "change[currency_to_id]" , :class => "select2" ) %>
   </div>

   <div class="field">
     <label>Tipo de cambio:</label>
     <%= select_tag( :type_change_id, options_for_select(@type_changes.map { |c| [c.name, c.id]  } ) , :id => 'change_currency_to', :name => "change[type_change_id]" , :class => "select2" ) %>
   </div>

   <div class="actions">
    <%= f.submit  :class => "btn btn-primary" %>
  </div>

  <% end %>
</div>

<div class="col-md-4"></div>
<div class="col-md-4"></div>
</div>

app/views/changes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de categorias</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Desde</th>
      <th>A</th>
      <th>Categoria</th>
      <th>Fecha desde</th>
      <th>Fecha hasta</th>
      <th>Relacion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @changes.each do |change| %>
    <tr>
      <td><%= change.type_change.currency_from.name %></td>
      <td><%= change.type_change.currency_to.name %></td>
      <td><%= change.type_change.category.name %></td>
      <td><%= change.start_dt %></td>
      <td><%= change.end_dt %></td>
      <td><%= change.amount %></td>
      <td><%= link_to 'Ver', change , :class => "btn btn-info" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/changes/new.html.erb
<h1>Nuevo Cambio</h1>

<%= render 'form' %>

<%= link_to 'Volver', changes_path, :class => "btn btn-default" %>

app/views/changes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Desde:</strong>
  <%= @change.type_change.currency_from.name %>
</p>

<p>
  <strong>A:</strong>
  <%= @change.type_change.currency_to.name %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @change.type_change.category.name %>
</p>

<p>
  <strong>Fecha desde:</strong>
  <%= @change.start_dt %>
</p>

<p>
  <strong>Fecha hasta:</strong>
  <%= @change.end_dt %>
</p>
<p>
  <strong>Relación:</strong>
  <%= @change.amount %>
</p>

<%= link_to 'Back', changes_path , :class => "btn btn-default"%>