config/routes.rb
Rails.application.routes.draw do
  resources :currencies
  resources :categories
  resources :type_changes
  resources :changes
  resources :exchange_parities

  root 'currencies#index'

end

app/models/currency.rb
class Currency < ActiveRecord::Base
	has_many :type_change, class_name: 'TypeChange', foreign_key: 'currency_from_id' 
	validates :name, :description, :abbreviation, presence: true 
  validates :name, uniqueness: { case_sensitive: false }

  def drop_logic
    self.drop=true
  end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_action :set_currency, only: [:show, :edit, :update, :destroy]

  # GET /currencies
  # GET /currencies.json
  def index
    @currencies = Currency.where(drop: :false)
  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
  end

  # GET /currencies/new
  def new
    @currency = Currency.new
  end

  # GET /currencies/1/edit
  def edit
  end

  # POST /currencies
  # POST /currencies.json
  def create
    @currency = Currency.new(currency_params)

    respond_to do |format|
      if @currency.save
        format.html { redirect_to currencies_path, notice: 'La moneda fue creada con exito.' }
        format.json { render :show, status: :created, location: @currency }
      else
        format.html { render :new }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /currencies/1
  # PATCH/PUT /currencies/1.json
  def update
    respond_to do |format|
      if @currency.update(currency_params)
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { render :show, status: :ok, location: @currency }
      else
        format.html { render :edit }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency.drop_logic
    @currency.save
    respond_to do |format|
      format.html { redirect_to currencies_url, notice: 'Currency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currency
      @currency = Currency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def currency_params
      params.require(:currency).permit(:description, :name, :abbreviation)
    end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_form.html.erb
<div class="row">
  <div class="col-md-2">
    <%= simple_form_for(@currency) do |f| %>
    <div class="form-group">
      <%= f.input :name %>
    </div>
    <div class="form-group">
      <%= f.input :description %> 
    </div>
    <div class="form-group">
      <%= f.input :abbreviation %>
    </div>
    <div class="actions">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
    <% end %>
  </div>
  <div class="col-md-2"></div>
  <div class="col-md-4"></div>
  <div class="col-md-4"></div>
</div>

app/views/currencies/edit.html.erb
<h1>Editing Currency</h1>

<%= render 'form' %>

app/views/currencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de monedas</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>MONEDA</th>
      <th>DESCRIPCIÓN</th>
      <th>ABREVIACIÓN</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @currencies.each do |currency| %>
      <tr>
        <td><%= currency.name %></td>
        <td><%= currency.description %></td>
        <td><%= currency.abbreviation %></td>
        <td><%= link_to 'Ver', currency , {:class => "btn btn-info"} %></td>
        <td><%= link_to 'Editar', edit_currency_path(currency) , :class => "btn btn-default" %></td>
        <td><%= link_to 'Eliminar', currency, method: :delete, data: {confirm: 'Esta seguro que desea eliminar?'}, :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Moneda', new_currency_path , :class => "btn btn-default" %>

app/views/currencies/new.html.erb
<h1>Nueva Moneda</h1>

<%= render 'form' %>

<%= link_to 'Volver', currencies_path , :class => "btn btn-default" %>

app/views/currencies/show.html.erb
<div class="row">
  <div class="col-md-2">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Moneda:</strong>
      <%= @currency.name %>
    </p>

    <p>
      <strong>Descripción:</strong>
      <%= @currency.description %>
    </p>


    <p>
      <strong>Abreviación:</strong>
      <%= @currency.abbreviation %>
    </p>

    <%= link_to 'Editar', edit_currency_path(@currency) , :class => "btn btn-default"%>
  </div>
  <div class="col-md-2"></div>
  <div class="col-md-4"></div>
  <div class="col-md-4"></div>
</div>