config/routes.rb
Rails.application.routes.draw do
  resources :currencies
  resources :categories
  resources :type_changes
  resources :changes
  resources :exchange_parities

  root 'currencies#index'

end

app/models/type_change.rb
class TypeChange < ActiveRecord::Base
  belongs_to :currency_to  ,  class_name: "Currency"  
  belongs_to :currency_from, class_name: "Currency" 
  belongs_to :category, class_name: "Category"
  has_many   :all_changes, class_name: "Change"

  validates :currency_from, :currency_to, :category ,:difference,:start_dt, presence: true
  validate :validate_distinct_currency, :validate_exist

  before_validation :set_start

  def validate_distinct_currency
    if currency_from_id == currency_to_id
      errors.add(:currency_from_id, "no puede ser igual a Moneda hasta")
    end
  end

  def set_start
    self.start_dt=Date.today
  end

  def validate_exist
    if not TypeChange.where(currency_from_id: currency_from_id , currency_to_id: currency_to_id, category_id: category_id ).empty?
      errors.add(:id, "Este cambio ya existe")
    end
  end


  def current
    self.all_changes.last
  end

  #method for calendar
  def current_for_date(date)
    changes_for_date=[]
    curr_for_date=self.all_changes.reverse.select {|n| Date.parse(n.start_dt.to_s) <= Date.parse(date)}

    changes_for_date << curr_for_date
    changes_for_date << curr_for_date.each {|n| self.all_changes.select }
   # changes_for_date << self.change_historicals.select {|chan| chan.start_dt = curr_for_date.end_dt } unless curr_for_date.end_dt.nil?
    changes_for_date

  end

  # changes_for_date=[]
  # curr_for_date=self.change_historicals.reverse.detect {|n| Date.parse(n.start_dt.to_s) <= Date.parse(date)}
  # changes_for_date << curr_for_date
  # changes_for_date << self.change_historicals.detect {|chan| chan.start_dt = curr_for_date.end_dt } unless curr_for_date.end_dt.nil?
  # changes_for_date

end

app/controllers/type_changes_controller.rb
class TypeChangesController < ApplicationController
  before_action :set_type_change, only: [:show , :edit]

  def index
    #@changes=Change.order(:currency_from_id, :currency_to_id)
    @typeChanges=TypeChange.joins(:category, :currency_from, :currency_to).where(categories: {drop: false}, currencies: {drop: false}, currency_tos_type_changes:{drop:false}).order(:id)
  end

  def show
  end

  def edit
  end

  def new
    @currencies=Currency.where(drop: :false)
    @category=Category.where(drop: :false)
    @typeChange=TypeChange.new
  end

  def create
    @typeChange=TypeChange.new(type_change_params)
    respond_to do |format|
      if @typeChange.save
        format.html { redirect_to @typeChange, notice: 'Cambio ha sido creado correctamente.' }
          #format.json { render :show, status: :created, location: @currency }
        else
          format.html { 
            @currencies=Currency.where(drop: :false)
            @category=Category.where(drop: :false)
            render :new }
          #format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end


  private
      # Use callbacks to share common setup or constraints between actions.
    def set_type_change
      @typeChange = TypeChange.find(params[:id])
    end

    def type_change_params
      params.require(:type_change).permit(:currency_from_id, :currency_to_id, :category_id, :difference )
    end


end

app/helpers/type_changes_helper.rb
module TypeChangesHelper
end

app/views/type_changes/_form.html.erb
<div class="row">
  <div class="col-md-2">
    <%= simple_form_for(@typeChange) do |f| %>
    <div class="field">
      <%= f.association :currency_from, input_html: { class: 'select2 ' }%>
    </div>

    <div class="field">
      <%= f.association :currency_to, input_html: { class: 'select2 ' }%>
    </div>

   <div class="field">
       <%= f.association :category, input_html: { class: 'select2 ' }%>
   </div>
    <div class="field">
      <%= f.input :difference  , as: :float, input_html: { value: 0 } %>
    </div>

   <div class="actions">
    <%= f.submit  :class => "btn btn-primary" %>
  </div>

  <% end %>
</div>

<div class="col-md-4"></div>
<div class="col-md-4"></div>
</div>

app/views/type_changes/edit.html.erb
<h1>Editar tipo de cambio</h1>

<%= render 'form' %>

app/views/type_changes/index.html.erb
<div class="row">
 <div class="col-md-1">
 </div>
 <div class="col-md-10">
   <p id="notice"><%= notice %></p>

   <h1>Lista de Paridad Actual</h1>
   <div class="grilla">
     <table class="table table-bordered ">
      <thead>
        <tr class="info">
          <th>Relación</th>
          <th>Descripción</th>
          <th>Historial</th>
        </tr>
      </thead>
      <% currency_from = ' ' %>
      <% currency_to = ' ' %>
      <tbody>
        <% @typeChanges.each do | typeChange | %>
        <% if  typeChange.currency_from.name != currency_from or typeChange.currency_to.name != currency_to %>
        <tr  class="tr-body-especial success">
          <td colspan="3" style="text-align: center" >
            <%= typeChange.currency_from.name + " / " + typeChange.currency_to.name %>
          </td>
          <% currency_from = typeChange.currency_from.name %>
          <% currency_to = typeChange.currency_to.name %>
        </tr>
        <% end %>
        <tr class="info">
          <td><%= number_with_precision(typeChange.current.amount, precision: 2, separator: '.', strip_insignificant_zeros: true)  unless typeChange.current.nil? %></td>
          <td><%= typeChange.category.name %></td>
          <td class= <%=typeChange.id %> > Ver Para:
           <%= date_field(:change, typeChange.id, class: 'input-sm') %>
           <div id="historic<%= typeChange.id %>"></div>
         </td>
       </tr>

       <% end %>
     </tbody>
   </table>
 </div>

 <br>
 <%= link_to 'Nuevo Tipo de Cambio', new_type_change_path ,  :class => "btn btn-default" %>
 <%= link_to 'Nuevo Cambio',  new_exchange_parity_path ,  :class => "btn btn-default" %>
</div>
<div class="col-md-1"></div>
</div>

app/views/type_changes/new.html.erb
<h1>Nuevo Cambio</h1>

<%= render 'form' %>

<%= link_to 'Volver', type_changes_path, :class => "btn btn-default" %>

app/views/type_changes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Desde:</strong>
  <%= @typeChange.currency_from.name %>
</p>

<p>
  <strong>A:</strong>
  <%= @typeChange.currency_to.name %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @typeChange.category.name %>
</p>
<p>
  <strong>Diferencia:</strong>
  <%= @typeChange.difference %>
</p>

<p>
  <strong>Fecha de inicio:</strong>
  <%= @typeChange.start_dt %>
</p>

<p>
  <strong>Fecha de fin:</strong>
  <%= @typeChange.end_dt %>
</p>


<%= link_to 'Edit', edit_type_change_path(@typeChange) , :class => "btn btn-default" %> |
<%= link_to 'Back', type_changes_path , :class => "btn btn-default"%>