config/routes.rb
Rails.application.routes.draw do
  resources :currencies
  resources :categories
  resources :type_changes
  resources :changes
  resources :exchange_parities

  root 'currencies#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many  :type_change
  validates :name , presence: true
  validates :name, uniqueness: { case_sensitive: false }

  def drop_logic
    self.drop=true
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
   before_action :set_category, only: [:show , :edit, :destroy]

  def index
    @categories=Category.where(drop: :false)
  end

  def show
  end

  def new
    @category=Category.new
  end

  def edit
  end

  def create
    @category=Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'La categoria se ha creado correctamente.' }
        #format.json { render :show, status: :created, location: @currency }
      else
        format.html { render :new }
        #format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end    
  end

   def destroy
    @category.drop_logic
    @category.save
    respond_to do |format|
      format.html { redirect_to category_url, notice: 'Tipo de cambio fue eliminado.' }
      #format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="row">
  <div class="col-md-2">
    <%= simple_form_for(@category) do |f| %>
    <div class="field">

      <%= f.input :name %>
    </div>
    <div class="field">
      <%= f.input :start_dt, as: :date, input_html: { value:  Date.today.strftime("%F")  } ,html5: true  %>
    
    </div>
    <div class="actions">
      <%= f.submit  :class => "btn btn-primary" %>
    </div>
    <% end %>
  </div>
  <div class="col-md-2"></div>
  <div class="col-md-4"></div>
  <div class="col-md-4"></div>
</div>

app/views/categories/edit.html.erb
<h1>Editando Categoría</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de categorias</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Description</th>
      <th>Desde</th>
      <th>Hasta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= category.start_dt %></td>
      <td><%= category.end_dt %></td>
      <td><%= link_to 'Ver', category , :class => "btn btn-info" %></td>
      <td><%= link_to 'Editar', edit_category_path(category) , :class => "btn btn-default" %></td>
        <td><%= link_to 'Eliminar', category, method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-danger" %></td>


    </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Nueva Categoria', new_category_path ,  :class => "btn btn-default" %>

app/views/categories/new.html.erb
<h1>Nueva Categoria</h1>

<%= render 'form' %>

<%= link_to 'Volver', categories_path , :class => "btn btn-default" %>

app/views/categories/show.html.erb
<div class="row">
  <div class="col-md-4">
    <p id="notice"><%= notice %></p>
    <div class="field">
    <p>
      <strong>Tipo de cambio:</strong>
      <%= @category.name %>
    </p>

    <p>
      <strong>Fecha Desde:</strong>
      <%= @category.start_dt %>
    </p>

    <p>
      <strong>Fecha Hasta:</strong>
      <%= @category.end_dt %>
    </p>


   
  </div>
  
  <div class="col-md-4"></div>
  <div class="col-md-4"></div>
</div>